#!/bin/bash

# Wait until cur_hw field in System table becomes greater than 0
while true
do
    [[ `ovsdb-client transact '["OpenHalon",{ "op": "select","table": "System","where": [ ],"columns" : ["cur_hw"]}]' | sed -e 's/[{}]/''/g' -e 's/\\]//g' | sed s/\\]//g | awk -F: '{print $3}'` -gt 0 ]] && /bin/ls /var/run/openvswitch/ovs-vswitchd.pid && break
    echo "Waiting for cur_cfg value set to 1"
    sleep 1
done
