#!/bin/bash

MAXTIME=20
COUNTER=0
IS_SWITCH_UP=0

while [ $IS_SWITCH_UP -ne 1 ] && [ $COUNTER -lt $MAXTIME ]
do
    CUR_HW=`ovsdb-client transact '["OpenSwitch",{ "op": "select","table": "System","where": [ ],"columns" : ["cur_hw"]}]' | sed -e 's/[{}]/''/g' -e 's/\\]//g' | sed s/\\]//g | awk -F: '{print $3}'`
    SWITCHD="$(/bin/ls /var/run/openvswitch/ops-switchd.pid)"
    if [ $((CUR_HW)) -eq 1 ] && [ "$SWITCHD" = 0 ]; then
        echo "ops-switchd has come up"
        IS_SWITCH_UP=1
    fi
    if [ $IS_SWITCH_UP -ne 1 ]; then
        let COUNTER=COUNTER+1
        sleep 1
    fi
done

if [ $IS_SWITCH_UP -ne 1 ]; then
    echo "Script Run : Failure" >> /shared/logs
    echo "CUR_HW column : " $CUR_HW >> /shared/logs
    SWITCHD="Down"
    echo "Switch state : " $SWITCHD >> /shared/logs
    systemctl status >> /shared/logs
    systemctl --state=failed --all >> /shared/logs
    ps -ef >> /shared/logs
else
    echo "Script Run : Success" >> /shared/logs
fi
