#!/bin/bash

MAXTIME=60
COUNTER=0
IS_SWITCH_UP=0
CUR_HW=0
SWITCHD_PID=0

while [ $IS_SWITCH_UP -ne 1 ] && [ $COUNTER -lt $MAXTIME ]
do
    # Check if cur_hw column in System table is set to 1
    CUR_HW=`ovsdb-client transact '["OpenSwitch",{ "op": "select","table": "System","where": [ ],"columns" : ["cur_hw"]}]' | sed -e 's/[{}]/''/g' -e 's/\\]//g' | sed s/\\]//g | awk -F: '{print $3}'`

    # Check if ops-switchd PID file is created
    /bin/ls /var/run/openvswitch/ops-switchd.pid
    SWITCHD_PID="$?"

    if [ $((CUR_HW)) -eq 1 ] && [ "$SWITCHD_PID" = 0 ]; then
        echo "ops-switchd has come up" >> /shared/logs
        IS_SWITCH_UP=1
    fi
    if [ $IS_SWITCH_UP -ne 1 ]; then
        let COUNTER=COUNTER+1
        sleep 1
    fi
done

if [ $CUR_HW -ne 1 ]; then
    # Please dont add any other echoes to write to /shared/logs before this one
    echo "CUR_HW Failure" >> /shared/logs
    echo "CUR_HW column: " $CUR_HW >> /shared/logs
    echo "ops-switchd PID status: " $SWITCHD_PID >> /shared/logs
    echo "Daemon Table:" >> /shared/logs
    ovs-vsctl list Daemon >> /shared/logs
    echo "Coredump:" >> /shared/logs
    coredumpctl gdb >> /shared/logs
    echo "All the running processes:" >> /shared/logs
    ps -aef >> /shared/logs
    systemctl status >> /shared/systemctl
    systemctl --state=failed --all >> /shared/systemctl
    ovsdb-client dump >> /shared/ovsdb_dump
elif [ $IS_SWITCH_UP -ne 1 ]; then
    # Please dont add any other to write to /shared/logs echoes before this one
    echo "Switchd Failure" >> /shared/logs
    echo "CUR_HW column: " $CUR_HW >> /shared/logs
    echo "ops-switchd PID status: " $SWITCHD_PID >> /shared/logs
    echo "Daemon Table:" >> /shared/logs
    ovs-vsctl list Daemon >> /shared/logs
    echo "Coredump:" >> /shared/logs
    coredumpctl gdb >> /shared/logs
    echo "All the running processes:" >> /shared/logs
    ps -aef >> /shared/logs
    systemctl status >> /shared/systemctl
    systemctl --state=failed --all >> /shared/systemctl
    ovsdb-client dump >> /shared/ovsdb_dump
else
    echo "Script Run : Success" >> /shared/logs
fi
